### ISSUE TITLE
can VDS3104 software running on ubuntu?

### ISSUE THREAD

**Issue by Jinwoo0503** [florentbr/OWON-VDS1022#101]
i try to run VDS3104 Software on Ubuntu 20.04 Desktop

i already try libusb-0.1.so.4, ch.ntb.usb-0.5.9.jar, libusbJava.so.old replace but not working with error log
```
$ LC_ALL=C java -jar ./plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
createUtilityPage!!!!
MainWindow
ch.ntb.usb.USBTimeoutException: LibusbJava.usb_bulk_read: Connection timed out
	at com.owon.uppersoft.vds.core.usb.CDevice.readBulk(CDevice.java:374)
	at com.owon.uppersoft.dso.source.usb.USBSource.acceptResponse(USBSource.java:135)
	at com.owon.uppersoft.dso.source.usb.USBSource.acceptResponse(USBSource.java:147)
	at com.owon.uppersoft.dso.circle.PortFilterSmart.collectPorts(PortFilterSmart.java:53)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:110)
	at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:94)
	at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:31)
	at com.owon.uppersoft.dso.circle.InfiniteDaemonSmart.onNotConnecting(InfiniteDaemonSmart.java:78)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:77)
	at com.owon.uppersoft.dso.global.WorkBenchSmart$3$1.run(WorkBenchSmart.java:182)
ch.ntb.usb.USBTimeoutException: LibusbJava.usb_bulk_read: Connection timed out
	at com.owon.uppersoft.vds.core.usb.CDevice.readBulk(CDevice.java:374)
	at com.owon.uppersoft.dso.source.usb.USBSource.acceptResponse(USBSource.java:135)
	at com.owon.uppersoft.dso.source.usb.USBSource.acceptResponse(USBSource.java:147)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.acceptResponse(USBSourceManager.java:45)
	at com.owon.uppersoft.dso.source.manager.SourceManager.acceptResponse(SourceManager.java:124)
	at com.owon.uppersoft.dso.source.comm.ext.InterCommSmart.checkMachine_1(InterCommSmart.java:349)
	at com.owon.uppersoft.dso.source.comm.ext.InterCommSmart.initMachine(InterCommSmart.java:296)
	at com.owon.uppersoft.dso.source.comm.detect.InitLinkRunner.initLink(InitLinkRunner.java:67)
	at com.owon.uppersoft.dso.source.comm.detect.InitLinkRunner.run(InitLinkRunner.java:31)
	at com.owon.uppersoft.dso.source.comm.Flow.doStuff(Flow.java:46)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:64)
	at com.owon.uppersoft.dso.global.WorkBenchSmart$3$1.run(WorkBenchSmart.java:182)

```

Can you give me some advice on how to solve this problem?

Just Need to run VDS3104 Software (Not Require Any Python APIs...)

**Comment by florentbr** [comment]
The software for the VDS3104 is different, but if it's also relying on the old libusbJava driver, then it should be possible to make it work on Linux. You'll have to de-compile the class raising the exception, fix the code, recompile the class and swap it in the jar. I have no idea why it's raising this exception. You'll have to figure out by writing some code (python or java) to to communicate with the device with the libusb driver.
