### ISSUE TITLE
Raspberry Pi No available USB found Resource temporarily unavailable

### ISSUE THREAD

**Issue by aaronnewcomb** [florentbr/OWON-VDS1022#76]
I tried installing on a fresh install of Raspbian today. Unfortunately, it looks like maybe libusbjava isn't working somehow? I am getting "No available USB found" in the GUI and Java errors on the command line.
`env: Linux, Java 17.0.6 arm
app dir: /opt/owon-vds-tiny
user dir: /root/.owon-vds-tiny
locale: en, en_US, false
ch.ntb.usb.USBException: LibusbJava.usb_open: Resource temporarily unavailable (-1568584872)
	at com.owon.uppersoft.vds.core.usb.CDevice.open(CDevice.java:86)
	at com.owon.uppersoft.vds.core.usb.CDevice.getDevices(CDevice.java:300)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:79)
	at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:74)
	at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:35)
	at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:37)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:79)
	at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:38)
`

**Comment by aaronnewcomb** [comment]
I also tried installing the version based on Debian Buster. Same result.

**Comment by florentbr** [comment]
Could you provide :
* the exact system architecture : `uname -a`
* the usb descriptor : `lsusb -v -s 5345`

**Comment by aaronnewcomb** [comment]
![image](https://user-images.githubusercontent.com/8517741/223508849-91796fe2-ae12-4103-995a-b9d510558ef1.png)
lsusb -v -s 5345 does not return anything. However, here is what shows up about the device when I just use lsusb -v ...
![image](https://user-images.githubusercontent.com/8517741/223509504-d20b1c0f-fc27-4c4f-ad0f-d4afde5e7288.png)

**Comment by aaronnewcomb** [comment]
BTW - I just tried this on a fresh install using a model 2B and it worked. Slowly of course, but it did work.

**Comment by florentbr** [comment]
> lsusb -v -s 5345 does not return anything.

My bad, it should be `lsusb -v -d 5345:1234`

> I tried installing on a fresh install of Raspbian today. Unfortunately, it looks like maybe libusbjava isn't working somehow?

The native `libusbjava.so`  provided here was compiled for `armhf`. It's likely the source of your issue since your system is `armv7l`. It should work once compiled to the correct architecture. Sources: https://github.com/florentbr/OWON-VDS1022/blob/master/lib/libusbJava-src.zip

> BTW - I just tried this on a fresh install using a model 2B and it worked. Slowly of course, but it did work.

Disable all the measures, it should improve the refresh rate.

**Comment by aaronnewcomb** [comment]
I don't think that armv71 could be the issue since it is working on my 2B and that is also running armv71.
![image](https://user-images.githubusercontent.com/8517741/223584361-c6887b85-b694-44aa-b199-ee296c60cb1b.png)
Also, on my 2B it doesn't show the resource temporarily unavailable in lsusb.

**Comment by florentbr** [comment]
Have a look at the system events. Maybe a driver is crashing or interfering with libusb.
Note that one has a linux kernel  `v7+` while the other is `v7l+`. So it could still be related to the compiled architecture.

**Comment by aaronnewcomb** [comment]
So, thinking this may be related to the architecture I decided to try 64bit Raspbian since that will be different again. And ... it works when compiled on this architecture. 
![image](https://user-images.githubusercontent.com/8517741/223634151-9134a35d-b419-4225-b308-f7592ee864d7.png)
So, I am going to call this good enough for now. Perhaps this will resolve itself with future changes in the supporting architecture libraries. Maybe this will help someone else who is having a similar problem.

**Comment by nistvan86** [comment]
@aaronnewcomb is this a Raspberry Pi 4B? Does the software work with usable speed on that? The 2B was too slow as you mentioned.
(Sorry for hijacking the thread, but there's not much information available on the net about this.)

**Comment by aaronnewcomb** [comment]
Yes. it was a Raspberry Pi 4B. However, that was overkill. I ended up using an Orange Pi 3 board running their Ubuntu image and it works perfectly. I hooked it up to a 10" touchscreen and 3D printed a case to put everything in. It works like a champ and now I don't have to connect it to my desktop or laptop.

**Comment by nistvan86** [comment]
@aaronnewcomb thank you! Tested the install on a Pi4 with recent 64bit RaspberryPi OS and it was straightforward. Ordered a scope, I'm looking forward to it. :)

**Comment by rprohask** [comment]
I believe I'm seeing a problem similar to this using Debian Bookworm and Trixie on Raspberry Pi2 and Pi5

A Bookworm installation on a Pi2v1.1 (armv7) worked without trouble back in August 2024. 

All attempts to set up a new installed image of either bookworm or trixie gives the same "no available USB.."
error for the past month or so. Copying the old version of bookworm to a new microSD card results in a
working setup, which, if upgraded to the latest version, again reports "no available USB..".

If anybody has a suggestion for how to reveal what's wrong I'd gladly try to follow it. I'm not a programmer,
merely a crash test dummy at best 8-)

Thanks for reading,

bob prohaska
