### ISSUE TITLE
New VDS1022I cannot find USB driver

### ISSUE THREAD

**Issue by robil1** [florentbr/OWON-VDS1022#91]
Just received a new VDS1022I, installed OWON's latest software (OWON_VDS_C2_1.1.7_setup.exe) and scope works perfectly.

Installed JAVA from [Adoptium.net](http://adoptium.net/)  jdk-21.0.1+12
Installed Florentbr software, release 1.1.5-cf19, and app installs OK but shows "Offline" No available USB found.
Uninstalled OWON software and reinstalled Florentbr software and had same issue.

Purchased 11/29/2023 direct from OWON

Has OWON sourced another FPGA that is no longer compatible?

**Comment by florentbr** [comment]
There's been 2 official releases since I last checked the source code. So yes it could be an issue with the FPGA.
To update the firmwares, simply copy/past the FPGA bin files from the official install.
Post the logs from the command line. There's likely a clue in there about your issue.
Have you tried with Java 8 or 11 or 17 ?

**Comment by robil1** [comment]
I will install with different JAVA versions.

I don't know where to get and copy the original firmware .bin files to.   OWON zip file did not have any.
  (To update the firmware, simply copy/paste the FPGA bin files from the official install.)

**Comment by florentbr** [comment]
Use 7zip to open `OWON_VDS_C2_1.1.7_Setup.exe` like a zip or check in "Program Files (x86)" once installed.

**Comment by robil1** [comment]
Open'd OWON_VDS_C2_1.1.7_Setup.exe with 7Zip and replaced files in fwa dir.
 Installed with success. "Offline" No available USB found. Tried another USB 2.0 and 3.0 port. No good.
Uninstalled prior Java and reinstalled Oracle Java 8, 11 and 17.
 Each time installed with success. App showed "Offline" No available USB found. Tried another USB 2.0 and 3.0 port. No good.
Uninstalled prior Java and reinstalled Adoptium JDK 8 and 17. 
 Each time installed with success. App showed "Offline" No available USB found. Tried another USB 2.0 and 3.0 port. No good.

Tried the original OWON software and it found USB OK after each Java change.

I'm going to use the OWON software for now since I really don't understand how all this software works and I'm out of ideas. 
If I should stumble on a solution, I'll post an update.
Thanks for your help.


Here are my FPGA/STM/Board numbers for reference.

YM 2311   VDS1022_V2.3.1   2022.07.11

FPGA  GOWIN  GWIN-LV4LQ144C6/15  2117B  PP8P38.0

ARM GIGA DEVICE  GD32F303VET6  AUJB137  AC2220

**Comment by robil1** [comment]
Did a debug of the app and it repeats "java.lang.UnsatisfiedLinkError: C:\Program Files\OWON VDS1022\lib\LibusbJava.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform"

My system is an AMD 3600 running Windows 10 64bit with Oracle Java 8 32 and 64 bit installed.  I added "echo %PROCESSOR_ARCHITECTURE%" and it showed AMD64

Not sure if I need JAVA JDK.  I have the JRE installed but tried both previously.
________________________________________________________________________________________________________________
C:\Windows\system32>java -version
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

C:\Program Files\OWON VDS1022>"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -Dsun.java2d.dpiaware=false -cp lib\* com.owon.vds.tiny.Main
env: Windows 10, Java 1.8.0_391 x86
app dir: C:\Program Files\OWON VDS1022
user dir: C:\Users\rbile\AppData\Local\OWON VDS1022
locale: en, en_US, false
java.lang.UnsatisfiedLinkError: C:\Program Files\OWON VDS1022\lib\LibusbJava.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at ch.ntb.usb.LibusbJava.load(LibusbJava.java:407)
        at ch.ntb.usb.LibusbJava.<clinit>(LibusbJava.java:386)
        at com.owon.uppersoft.vds.core.usb.CDevice.init(CDevice.java:213)
        at com.owon.uppersoft.vds.core.usb.CDevice.getDevices(CDevice.java:229)
        at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:79)
        at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:74)
        at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:35)
        at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:37)
        at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:79)
        at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:38)
java.lang.NoClassDefFoundError: Could not initialize class ch.ntb.usb.LibusbJava
        at com.owon.uppersoft.vds.core.usb.CDevice.init(CDevice.java:213)
        at com.owon.uppersoft.vds.core.usb.CDevice.getDevices(CDevice.java:229)
        at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:79)
        at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:74)
        at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:35)
        at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:37)
        at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:79)
        at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:38)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: C:\Program Files\OWON VDS1022\lib\LibusbJava.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform [in thread "Thread-4"]
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at ch.ntb.usb.LibusbJava.load(LibusbJava.java:407)
        at ch.ntb.usb.LibusbJava.<clinit>(LibusbJava.java:386)
        ... 8 more

**Comment by florentbr** [comment]
Your second command line has a hard link to a different 32bits JRE (`java.exe`) and the app was installed as 64bits. This is the reason for this error. Did you get it from the Windows shortcut or in launch.cmd ?

The `java` in your `PATH` environment variable is 64bits. So to match the bitness, execute `java -Dsun.java2d.dpiaware=false -cp lib* com.owon.vds.tiny.Main` while in `C:\Program Files\OWON VDS1022`.

No need for a JDK, a JRE is enough. You can test different JRE without install (just unzip)  and use a hard link to `bin\java.exe` in the command line.

**Comment by robil1** [comment]
Success
I finally have your app running and it is excellent.
Going down a rabbit hole and decided to remove all Java and OWON VDS1022 file traces with Revo Uninstaller and download Oracle Java jre-8u391-windows-x64 .exe and your app.  Installed JAVA, compiled your code, plugged in my scope and your app worked. I learned a lot (I'm not a programmer) going through this exercise and really appreciate your support. Have a great Holiday...
