### ISSUE TITLE
MultiComp Pro MP720019 not detected

### ISSUE THREAD

**Issue by Craigp23** [florentbr/OWON-VDS1022#99]
I'm attempting to connect a MultiComp Pro MP720019 on a laptop running Ubuntu 22.04 

With the MP720019 connected via USB I'm seeing the following log :

`owon-vds-tiny
env: Linux, Java 11.0.23 amd64
app dir: /opt/owon-vds-tiny
user dir: /home/kyla/.owon-vds-tiny
locale: en, en_GB, false
Gtk-Message: 21:31:49.953: Failed to load module "canberra-gtk-module"
[Send @MACHINE_TYPE_ADD 0x56]LibusbJava.usb_bulk_read: Connection timed out
ch.ntb.usb.USBException: LibusbJava.usb_claim_interface: Device or resource busy
	at com.owon.uppersoft.vds.core.usb.CDevice.open(CDevice.java:91)
	at com.owon.uppersoft.vds.core.usb.CDevice.getDevices(CDevice.java:300)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:79)
	at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:74)
	at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:35)
	at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:37)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:79)
	at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:38)
[Send @MACHINE_TYPE_ADD 0x56]LibusbJava.usb_bulk_read: Connection timed out
ch.ntb.usb.USBException: LibusbJava.usb_claim_interface: Device or resource busy
`
I noticed that the MP720019 isn't specifically mentioned in the Readme although its family members are. Is that an issue?

Appreciate your help getting this working, TIA :)

**Comment by florentbr** [comment]
The software for the MP720019 is different. It won't work.
The binaries provided here are for the VDS1022, MP720016 or MP720017.
